# Generated by Django 5.1.4 on 2025-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="for_disease",
        ),
        migrations.AddField(
            model_name="medicine",
            name="for_diseases",
            field=models.ManyToManyField(related_name="medicines", to="core.disease"),
        ),
    ]
