# Generated by Django 5.1.4 on 2025-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_disease_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="John", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(default="jhon", max_length=50),
            preserve_default=False,
        ),
    ]
